languageCode = "en-us"
title = "bampfa documentation"
baseURL = "https://bam-pfa.github.io/BAMPFA-documentation/"

theme="hugo-theme-docdock"
unfoldedMenus = ["start"]

publishDir = "docs"

[outputs]
home = [ "HTML", "RSS", "JSON"]
