languageCode = "en-us"
title = "bampfa documentation"
baseURL = "BAMPFA-documentation/"


theme="hugo-theme-docdock"
unfoldedMenus = ["start"]


publishDir = "docs"


[outputs]
home = [ "HTML", "RSS", "JSON"]